#!/usr/bin/expect -f
set timeout -1
set server_ip 192.168.245.20
set switch_user administrator
set switch_pass Nocompromise75!!
set image cat9k_iosxe.17.09.03m3.SPA.bin
set DATE [timestamp -format %Y%m%d]
log_file /root/.meraki_mig/logs/$DATE.log
set fh [open /root/.meraki_mig/ip_list r]

set expected_value_user "default_user"
spawn echo "$switch_user"
expect -re expect -re "$expected_value_user"
if { $expect_out(buffer) eq $expected_value_user } {
  puts "The variable $switch_user is the set default. Did you modify Global Environment Settings?"
  exit
} else {
  puts " "
}

set expected_value_pass "default_pass"
spawn echo "$switch_pass"
expect -re expect -re "$expected_value_pass"
if { $expect_out(buffer) eq $expected_value_pass } {
  puts "The variable $switch_pass is the set default. Did you modify Global Environment Settings?"
  exit
} else {
  puts " "
}

set expected_value_server "default_server"
spawn echo "$server_ip"
expect -re expect -re "$expected_value_server"
if { $expect_out(buffer) eq $expected_value_server } {
  puts "The variable $server_ip is the set default. Did you modify Global Environment Settings?"
  exit
} else {
  puts " "
}
while {[gets $fh ip] != -1} {
spawn rm /root/.ssh/known_hosts
spawn ssh $switch_user@$ip
expect "])? "
send -- "yes\r"
expect "Password: "
send -- "$switch_pass\r"
expect "*#"
send -- "logout\r"
spawn ssh $switch_user@$ip
expect "Password: "
send -- "$switch_pass\r"
expect "*#"
send "conf t\r"
expect "*#"
send -- "file prompt quiet\r"
expect "*#"
send -- "do wr\r"
expect "*#"
send -- "do copy running-config tftp://$server_ip/$ip\r"
expect "*#"
send -- "do show ip int br | redirect tftp://$server_ip/$ip-shipintbr\r"
expect "*#"
send -- "do show ip name-servers | redirect tftp://$server_ip/$ip-shipnm\r"
expect "*#"
send -- "do show version | redirect tftp://$server_ip/$ip-shver\r"
expect "*#"
send -- "do sh ip route | redirect tftp://$server_ip/$ip-shroute\r"
expect "*#"
send -- "do show vlan | redirect tftp://$server_ip/$ip-shvlan\r"
expect "*#"
send -- "do install remove inactive\r"
#expect "*n]"
#send -- "y\r"
expect {
    "*n]" {send -- "y\r"
      exp_continue
    }
    "*#" {send -- "exit\r"

    }
}
}
close $fh
