#!/bin/bash
#Meraki Main Menu
TEXTRESET=$(tput sgr0)
RED=$(tput setaf 1)
YELLOW=$(tput setaf 3)
GREEN=$(tput setaf 2)
SERVERIP=$(hostname -I)

items=(1 "Catalyst Migration for c9300 Series Switches"
  2 "Catalyst Monitoring for Wireless (Coming Soon!)"
)

while choice=$(dialog --title "$TITLE" \
  --backtitle "CMDS-->Main Menu" \
  --menu "Please select" 30 65 3 "${items[@]}" \
  2>&1 >/dev/tty); do
  case $choice in
  1) clear & /root/.meraki_mig/menu.sh ;;
  2) clear ;;
esac
done
clear # clear after user pressed Cancel
