#!/bin/bash
#Meraki Main Menu
TEXTRESET=$(tput sgr0)
RED=$(tput setaf 1)
YELLOW=$(tput setaf 3)
GREEN=$(tput setaf 2)
SERVERIP=$(hostname -I)
VERSION=$(cat /root/.meraki_mig/version)
clear
echo "VERSION=${VERSION}
${GREEN}

****************************************************************
                    Welcome to CMDS
****************************************************************
${TEXTRESET}

At Any time, you can type ${YELLOW}meraki_migration${TEXTRESET} from the cli to access the menu
"
sleep 4

items=(1 "-----------Catalyst Switching Tools-----------"
  2 "Catalyst Migration for c9300 Series Switches"
  3 "Catalyst Monitoring for Switching Prep Tool"
  4 " Legacy Catalyst Port Migration - BETA"
  5 " "
  6 "-----------Catalyst Wireless Tools-----------"
  7 "      Catalyst Monitoring for Wireless"
  8 " "
  9 "----------------Server Tools-----------------"
 10 "             Server Configuration"
 11 "          DHCP Server Configuration"
 12 " "
 13 "---------------------------------------------"
 14 "             Welcome to CMDS"
)

while choice=$(dialog --title "$TITLE" \
  --backtitle "CMDS-->Main Menu" \
  --menu "Please Select" 30 75 30 "${items[@]}" \
  2>&1 >/dev/tty); do
  case $choice in
  1) clear ;;
  2) clear & /root/.meraki_mig/menu.sh ;;
  3) clear & /root/.meraki_mon_switch/menu.sh ;;
  4) clear & /root/.meraki_port_mig/menu.sh ;;
  5) clear ;;
  6) clear ;;
  7) clear & /root/.meraki_mon_wlc/menu.sh ;;
  8) clear ;;
  9) clear ;;
 10) clear & /root/.meraki_mig/server-tools.sh ;;
 11) clear & /root/.servman/DHCPMan ;;
 12) clear ;;
 13) clear ;;
 14) clear & /root/.meraki_mig/welcome.readme ;;
esac
done
clear # clear after user pressed Cancel
