#!/bin/bash
#Meraki Main Menu
TEXTRESET=$(tput sgr0)
RED=$(tput setaf 1)
YELLOW=$(tput setaf 3)
GREEN=$(tput setaf 2)
SERVERIP=$(hostname -I)
clear
echo "
${GREEN}
v1.02(1)
****************************************************************
                    Welcome to CMDS
****************************************************************
${TEXTRESET}

At Any time, you can type ${YELLOW}meraki_migration${TEXTRESET} from the cli to access the menu
"
sleep 4

items=(1 "--------Catalyst Switching Tools--------"
  2 "Catalyst Migration for c9300 Series Switches"
  3 "Catalyst Monitoring for Switching Prep Tool"
  4 " "
  5 "--------Catalyst Wireless Tools--------"
  6 "Catalyst Monitoring for Wireless"
  7 " "
  8 "------------Server Tools-----------"
  9 "Server Configuration"


)

while choice=$(dialog --title "$TITLE" \
  --backtitle "CMDS-->Main Menu" \
  --menu "Please Select" 30 75 3 "${items[@]}" \
  2>&1 >/dev/tty); do
  case $choice in
  1) clear ;;
  2) clear & /root/.meraki_mig/menu.sh ;;
  3) clear & /root/.meraki_mon_switch/menu.sh ;;
  4) clear ;;
  5) clear ;;
  6) clear & /root/.meraki_mon_wlc/menu.sh ;;
  7) clear ;;
  8) clear ;;
  9) clear & /root/.meraki_mig/server-tools.sh ;;
esac
done
clear # clear after user pressed Cancel
