#!/bin/bash
#!/bin/bash
TEXTRESET=$(tput sgr0)
RED=$(tput setaf 1)
YELLOW=$(tput setaf 3)
GREEN=$(tput setaf 2)
USER=$(whoami)

#Checking for user permissions
if [ "$USER" = "root" ]; then
echo " "
else
  echo ${RED}"This program must be run as root ${TEXTRESET}"
  echo "Exiting"
fi
clear
cat << EOF
${GREEN}DHCP Server Management${TEXTRESET}
${GREEN}Edit DHCP Config${TEXTRESET}
EOF

echo "After you edit this config file, you must restart the DHCP server Service"

nano /etc/dhcp/dhcpd.conf


while true; do
   read -p "Would you like to restart the DHCP service now? (y/n) " yn
   case $yn in
   [yY])
      systemctl restart dhcpd
      break
      ;;
   [nN])
      echo exiting...
      exit
      ;;
   *) echo invalid response ;;
   esac
done
