#!/bin/bash
TEXTRESET=$(tput sgr0)
RED=$(tput setaf 1)
YELLOW=$(tput setaf 3)
GREEN=$(tput setaf 2)
USER=$(whoami)

#Checking for user permissions
if [ "$USER" = "root" ]; then
echo " "
else
  echo ${RED}"This program must be run as root ${TEXTRESET}"
  echo "Exiting"
fi
clear
cat << EOF
${GREEN}DHCP Server Management${TEXTRESET}
${GREEN}Enable DHCP Service${TEXTRESET}
EOF

systemctl enable dhcpd

systemctl --type=service --all | grep dhcpd

read -p "Press Any Key"
