#!/bin/bash
TEXTRESET=$(tput sgr0)
RED=$(tput setaf 1)
YELLOW=$(tput setaf 3)
GREEN=$(tput setaf 2)
USER=$(whoami)

#Checking for user permissions
if [ "$USER" = "root" ]; then
echo " "
else
  echo ${RED}"This program must be run as root ${TEXTRESET}"
  echo "Exiting"
fi
clear
cat << EOF
${GREEN}DHCP Server Management${TEXTRESET}
${RED}Stop DHCP Service${TEXTRESET}
${YELLOW} *To Exit this screen press the "q" key${TEXTRESET}


EOF

systemctl stop dhcpd
ps -ax | grep dhcp | head

cat <<EOF
Checking Status 
EOF

systemctl status dhcpd
sleep 3

